name: Build APK

on:
  push:
    branches: [ main, master ]

jobs:
  build-apk:
    name: Build Expo APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup Expo CLI
        run: npm install -g eas-cli

      - name: Install Dependencies
        run: npm install

      - name: Build APK
        run: eas build -p android --profile preview --non-interactive
        env:
          EAS_BUILD_PROFILE: preview
          EXPO_USERNAME: ${{ secrets.EXPO_USERNAME }}
          EXPO_PASSWORD: ${{ secrets.EXPO_PASSWORD }}

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          path: /github/workspace/dist/*.apk
