name: Build APK (Using EXPO_TOKEN)

on:
  push:
    branches: [ main, master ]

jobs:
  build-apk:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your code
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Setup Node.js 20
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      # 3. Install EAS CLI globally
      - name: Install EAS CLI
        run: npm install -g eas-cli

      # 4. Install project dependencies
      - name: Install Dependencies
        run: npm install

      # 5. Build the APK using EXPO_TOKEN
      - name: Build APK
        run: eas build -p android --profile preview --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      # 6. Upload the generated APK
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          path: dist/*.apk
          if-no-files-found: error
          retention-days: 3
